-- PostgreSQL schema for backend/db/models.py
-- Run with: psql "$DATABASE_URL" -f postgresql_schema.sql

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    display_name VARCHAR(50),
    nickname VARCHAR(50),
    avatar_path TEXT,
    avatar_url TEXT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    session_version INTEGER NOT NULL DEFAULT 0,
    daily_free_quota INTEGER NOT NULL DEFAULT 100,
    daily_free_used INTEGER NOT NULL DEFAULT 0,
    daily_free_quota_date VARCHAR(10),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_provider_configs (
    id VARCHAR(36) PRIMARY KEY,
    category VARCHAR(20) NOT NULL,
    name VARCHAR(100) DEFAULT '',
    is_active BOOLEAN DEFAULT FALSE,
    api_key TEXT DEFAULT '',
    base_url TEXT DEFAULT '',
    model_name VARCHAR(100) DEFAULT '',
    light_model_name VARCHAR(100) DEFAULT '',
    supports_function_calling BOOLEAN DEFAULT TRUE,
    use_doc_orientation BOOLEAN DEFAULT FALSE,
    use_doc_unwarping BOOLEAN DEFAULT FALSE,
    use_chart_recognition BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_verifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    code_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_sent_at TIMESTAMP WITHOUT TIME ZONE,
    attempts INTEGER DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(50) NOT NULL,
    subject VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tag_subject UNIQUE (tag_name, subject)
);

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) UNIQUE,
    user_id INTEGER REFERENCES users(id),
    name VARCHAR(100) NOT NULL,
    project_type VARCHAR(20) NOT NULL DEFAULT 'question',
    summary VARCHAR(200) DEFAULT '',
    description TEXT DEFAULT '',
    color VARCHAR(20) DEFAULT '#2563eb',
    icon VARCHAR(50) DEFAULT 'book-open',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS provider_configs (
    id VARCHAR(36) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    category VARCHAR(20) NOT NULL,
    name VARCHAR(100) DEFAULT '',
    is_active BOOLEAN DEFAULT FALSE,
    api_key TEXT DEFAULT '',
    base_url TEXT DEFAULT '',
    model_name VARCHAR(100) DEFAULT '',
    light_model_name VARCHAR(100) DEFAULT '',
    supports_function_calling BOOLEAN DEFAULT TRUE,
    use_doc_orientation BOOLEAN DEFAULT FALSE,
    use_doc_unwarping BOOLEAN DEFAULT FALSE,
    use_chart_recognition BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_model_selections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    category VARCHAR(20) NOT NULL,
    source VARCHAR(20) NOT NULL,
    provider_id VARCHAR(36) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    option_id VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_model_selection_category UNIQUE (user_id, category)
);

CREATE TABLE IF NOT EXISTS quota_usage_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    action_type VARCHAR(32) NOT NULL,
    amount INTEGER NOT NULL DEFAULT 1,
    summary VARCHAR(120) NOT NULL DEFAULT '',
    quota_date VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS device_bindings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid VARCHAR(36) NOT NULL UNIQUE,
    user_id INTEGER NOT NULL REFERENCES users(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS upload_batches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    project_id INTEGER REFERENCES projects(id),
    original_filename VARCHAR(255) NOT NULL,
    subject VARCHAR(50),
    file_path TEXT,
    upload_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS split_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    subject VARCHAR(50),
    model_provider VARCHAR(20),
    file_names_json TEXT,
    original_images_json TEXT,
    questions_json TEXT,
    question_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workflow_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) UNIQUE,
    user_id INTEGER REFERENCES users(id),
    run_type VARCHAR(30) NOT NULL DEFAULT 'split',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    subject VARCHAR(50),
    model_provider VARCHAR(20),
    file_names_json TEXT,
    result_dir TEXT NOT NULL DEFAULT '',
    question_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    project_id INTEGER REFERENCES projects(id),
    batch_id INTEGER REFERENCES upload_batches(id),
    content_hash VARCHAR(64) NOT NULL,
    question_type VARCHAR(20),
    content_json TEXT,
    options_json TEXT,
    has_formula BOOLEAN DEFAULT FALSE,
    has_image BOOLEAN DEFAULT FALSE,
    image_refs_json TEXT,
    needs_correction BOOLEAN DEFAULT FALSE,
    ocr_issues_json TEXT,
    user_answer TEXT,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    review_status VARCHAR(10) DEFAULT '待复习',
    review_due_at TIMESTAMP WITHOUT TIME ZONE,
    review_last_at TIMESTAMP WITHOUT TIME ZONE,
    review_interval_days INTEGER NOT NULL DEFAULT 0,
    review_count INTEGER NOT NULL DEFAULT 0,
    ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    answer TEXT,
    CONSTRAINT uq_question_hash_user_project UNIQUE (content_hash, user_id, project_id)
);

CREATE TABLE IF NOT EXISTS question_embeddings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL UNIQUE REFERENCES questions(id),
    model_name VARCHAR(50) NOT NULL DEFAULT 'local-hash-v1',
    text_hash VARCHAR(64) NOT NULL,
    vector_json TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) UNIQUE,
    user_id INTEGER REFERENCES users(id),
    question_id INTEGER REFERENCES questions(id),
    title VARCHAR(255) DEFAULT '新对话',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES chat_sessions(id),
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS device_captures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid VARCHAR(36) NOT NULL REFERENCES device_bindings(device_uuid),
    user_id INTEGER NOT NULL REFERENCES users(id),
    file_key VARCHAR(32) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    content_type VARCHAR(100) DEFAULT '',
    file_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS question_tag_mapping (
    question_id INTEGER NOT NULL REFERENCES questions(id),
    tag_id INTEGER NOT NULL REFERENCES knowledge_tags(id),
    PRIMARY KEY (question_id, tag_id)
);

CREATE TABLE IF NOT EXISTS notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    project_id INTEGER REFERENCES projects(id),
    title VARCHAR(255) NOT NULL,
    subject VARCHAR(50),
    content_markdown TEXT DEFAULT '',
    source_images_json TEXT,
    ocr_text TEXT,
    review_due_at TIMESTAMP WITHOUT TIME ZONE,
    review_last_at TIMESTAMP WITHOUT TIME ZONE,
    review_interval_days INTEGER NOT NULL DEFAULT 0,
    review_count INTEGER NOT NULL DEFAULT 0,
    ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS note_tag_mapping (
    note_id INTEGER NOT NULL REFERENCES notes(id),
    tag_id INTEGER NOT NULL REFERENCES knowledge_tags(id),
    PRIMARY KEY (note_id, tag_id)
);

CREATE TABLE IF NOT EXISTS review_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    target_type VARCHAR(20) NOT NULL,
    target_id INTEGER NOT NULL,
    rating VARCHAR(20) NOT NULL,
    quality INTEGER NOT NULL DEFAULT 3,
    interval_days INTEGER NOT NULL DEFAULT 0,
    ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    reviewed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    next_due_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS ix_users_email ON users(email);

CREATE INDEX IF NOT EXISTS ix_email_verifications_email ON email_verifications(email);

CREATE INDEX IF NOT EXISTS ix_projects_public_id ON projects(public_id);
CREATE INDEX IF NOT EXISTS ix_projects_user_id ON projects(user_id);
CREATE INDEX IF NOT EXISTS ix_projects_project_type ON projects(project_type);

CREATE INDEX IF NOT EXISTS ix_provider_configs_user_id ON provider_configs(user_id);

CREATE INDEX IF NOT EXISTS ix_user_model_selections_user_id ON user_model_selections(user_id);
CREATE INDEX IF NOT EXISTS ix_user_model_selections_category ON user_model_selections(category);

CREATE INDEX IF NOT EXISTS ix_quota_usage_events_user_id ON quota_usage_events(user_id);
CREATE INDEX IF NOT EXISTS ix_quota_usage_events_action_type ON quota_usage_events(action_type);
CREATE INDEX IF NOT EXISTS ix_quota_usage_events_quota_date ON quota_usage_events(quota_date);
CREATE INDEX IF NOT EXISTS ix_quota_usage_events_created_at ON quota_usage_events(created_at);

CREATE INDEX IF NOT EXISTS ix_device_bindings_device_uuid ON device_bindings(device_uuid);
CREATE INDEX IF NOT EXISTS ix_device_bindings_user_id ON device_bindings(user_id);
CREATE INDEX IF NOT EXISTS ix_device_bindings_is_active ON device_bindings(is_active);
CREATE INDEX IF NOT EXISTS ix_device_bindings_created_at ON device_bindings(created_at);

CREATE INDEX IF NOT EXISTS ix_upload_batches_user_id ON upload_batches(user_id);
CREATE INDEX IF NOT EXISTS ix_upload_batches_project_id ON upload_batches(project_id);

CREATE INDEX IF NOT EXISTS ix_split_records_user_id ON split_records(user_id);
CREATE INDEX IF NOT EXISTS ix_split_records_created_at ON split_records(created_at);

CREATE INDEX IF NOT EXISTS ix_workflow_runs_public_id ON workflow_runs(public_id);
CREATE INDEX IF NOT EXISTS ix_workflow_runs_user_id ON workflow_runs(user_id);
CREATE INDEX IF NOT EXISTS ix_workflow_runs_run_type ON workflow_runs(run_type);
CREATE INDEX IF NOT EXISTS ix_workflow_runs_status ON workflow_runs(status);
CREATE INDEX IF NOT EXISTS ix_workflow_runs_created_at ON workflow_runs(created_at);

CREATE INDEX IF NOT EXISTS ix_questions_user_id ON questions(user_id);
CREATE INDEX IF NOT EXISTS ix_questions_project_id ON questions(project_id);
CREATE INDEX IF NOT EXISTS ix_questions_review_status ON questions(review_status);
CREATE INDEX IF NOT EXISTS ix_questions_review_due_at ON questions(review_due_at);
CREATE INDEX IF NOT EXISTS ix_questions_created_at ON questions(created_at);

CREATE INDEX IF NOT EXISTS ix_question_embeddings_question_id ON question_embeddings(question_id);

CREATE INDEX IF NOT EXISTS ix_chat_sessions_public_id ON chat_sessions(public_id);
CREATE INDEX IF NOT EXISTS ix_chat_sessions_user_id ON chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_chat_sessions_question_id ON chat_sessions(question_id);

CREATE INDEX IF NOT EXISTS ix_chat_messages_session_id ON chat_messages(session_id);

CREATE INDEX IF NOT EXISTS ix_device_captures_device_uuid ON device_captures(device_uuid);
CREATE INDEX IF NOT EXISTS ix_device_captures_user_id ON device_captures(user_id);
CREATE INDEX IF NOT EXISTS ix_device_captures_file_key ON device_captures(file_key);
CREATE INDEX IF NOT EXISTS ix_device_captures_created_at ON device_captures(created_at);

CREATE INDEX IF NOT EXISTS ix_notes_user_id ON notes(user_id);
CREATE INDEX IF NOT EXISTS ix_notes_project_id ON notes(project_id);
CREATE INDEX IF NOT EXISTS ix_notes_review_due_at ON notes(review_due_at);
CREATE INDEX IF NOT EXISTS ix_notes_created_at ON notes(created_at);

CREATE INDEX IF NOT EXISTS ix_review_events_user_id ON review_events(user_id);
CREATE INDEX IF NOT EXISTS ix_review_events_target_type ON review_events(target_type);
CREATE INDEX IF NOT EXISTS ix_review_events_target_id ON review_events(target_id);
CREATE INDEX IF NOT EXISTS ix_review_events_reviewed_at ON review_events(reviewed_at);
CREATE INDEX IF NOT EXISTS ix_review_events_next_due_at ON review_events(next_due_at);

-- 表注释
COMMENT ON TABLE users IS '用户表，保存账号、头像、配额和会话版本等基础信息';
COMMENT ON TABLE system_provider_configs IS '系统级模型或 OCR 服务商配置，由管理员维护，全站共享';
COMMENT ON TABLE email_verifications IS '邮箱验证码表，仅保存验证码哈希和发送状态';
COMMENT ON TABLE knowledge_tags IS '知识点标签表，题目和笔记共用';
COMMENT ON TABLE projects IS '学习项目表，用于按错题库、笔记库等空间组织内容';
COMMENT ON TABLE provider_configs IS '用户级模型或 OCR 服务商配置';
COMMENT ON TABLE user_model_selections IS '用户在不同模型类别下选择的默认模型';
COMMENT ON TABLE quota_usage_events IS '免费额度消耗事件表，用于统计今日用量和最近活动';
COMMENT ON TABLE device_bindings IS '硬件摄像头设备绑定表';
COMMENT ON TABLE upload_batches IS '上传批次表，记录原始上传文件及所属项目';
COMMENT ON TABLE split_records IS '试卷拆分历史记录表';
COMMENT ON TABLE workflow_runs IS '后端工作流运行记录表，用于跟踪拆题、识别等异步任务';
COMMENT ON TABLE questions IS '题目表，保存 OCR 后的题目结构、答案、复习状态等信息';
COMMENT ON TABLE question_embeddings IS '题目向量缓存表，用于自然语言检索';
COMMENT ON TABLE chat_sessions IS '对话会话表，可绑定题目，也可独立存在';
COMMENT ON TABLE chat_messages IS '对话消息表';
COMMENT ON TABLE device_captures IS '硬件摄像头上传图片记录表';
COMMENT ON TABLE question_tag_mapping IS '题目与知识点标签的多对多关联表';
COMMENT ON TABLE notes IS '笔记表，保存整理后的 Markdown 内容和复习状态';
COMMENT ON TABLE note_tag_mapping IS '笔记与知识点标签的多对多关联表';
COMMENT ON TABLE review_events IS '间隔复习事件表，记录题目或笔记的每次复习结果';

-- 用户表字段注释
COMMENT ON COLUMN users.id IS '用户自增主键';
COMMENT ON COLUMN users.username IS '登录或展示用用户名';
COMMENT ON COLUMN users.display_name IS '展示名称';
COMMENT ON COLUMN users.nickname IS '用户昵称';
COMMENT ON COLUMN users.avatar_path IS '头像本地存储路径';
COMMENT ON COLUMN users.avatar_url IS '头像访问 URL';
COMMENT ON COLUMN users.email IS '邮箱地址，唯一';
COMMENT ON COLUMN users.password_hash IS '密码哈希';
COMMENT ON COLUMN users.is_admin IS '是否为管理员';
COMMENT ON COLUMN users.session_version IS '会话版本号，用于强制旧登录失效';
COMMENT ON COLUMN users.daily_free_quota IS '每日免费额度';
COMMENT ON COLUMN users.daily_free_used IS '当日已使用免费额度';
COMMENT ON COLUMN users.daily_free_quota_date IS '免费额度统计日期，格式 YYYY-MM-DD';
COMMENT ON COLUMN users.created_at IS '创建时间';

-- 服务商配置字段注释
COMMENT ON COLUMN system_provider_configs.id IS '配置 UUID';
COMMENT ON COLUMN system_provider_configs.category IS '服务类别，如 openai、anthropic、paddleocr';
COMMENT ON COLUMN system_provider_configs.name IS '配置名称';
COMMENT ON COLUMN system_provider_configs.is_active IS '是否启用';
COMMENT ON COLUMN system_provider_configs.api_key IS 'API Key';
COMMENT ON COLUMN system_provider_configs.base_url IS '服务基础地址';
COMMENT ON COLUMN system_provider_configs.model_name IS '主模型名称';
COMMENT ON COLUMN system_provider_configs.light_model_name IS '轻量模型名称';
COMMENT ON COLUMN system_provider_configs.supports_function_calling IS '是否支持函数调用';
COMMENT ON COLUMN system_provider_configs.use_doc_orientation IS 'PaddleOCR 是否启用文档方向分类';
COMMENT ON COLUMN system_provider_configs.use_doc_unwarping IS 'PaddleOCR 是否启用文档矫正';
COMMENT ON COLUMN system_provider_configs.use_chart_recognition IS 'PaddleOCR 是否启用图表识别';
COMMENT ON COLUMN provider_configs.id IS '配置 UUID';
COMMENT ON COLUMN provider_configs.user_id IS '所属用户 ID';
COMMENT ON COLUMN provider_configs.category IS '服务类别，如 openai、anthropic、paddleocr';
COMMENT ON COLUMN provider_configs.name IS '配置名称';
COMMENT ON COLUMN provider_configs.is_active IS '是否启用';
COMMENT ON COLUMN provider_configs.api_key IS 'API Key';
COMMENT ON COLUMN provider_configs.base_url IS '服务基础地址';
COMMENT ON COLUMN provider_configs.model_name IS '主模型名称';
COMMENT ON COLUMN provider_configs.light_model_name IS '轻量模型名称';
COMMENT ON COLUMN provider_configs.supports_function_calling IS '是否支持函数调用';
COMMENT ON COLUMN provider_configs.use_doc_orientation IS 'PaddleOCR 是否启用文档方向分类';
COMMENT ON COLUMN provider_configs.use_doc_unwarping IS 'PaddleOCR 是否启用文档矫正';
COMMENT ON COLUMN provider_configs.use_chart_recognition IS 'PaddleOCR 是否启用图表识别';

-- 项目与上传字段注释
COMMENT ON COLUMN projects.id IS '项目自增主键';
COMMENT ON COLUMN projects.public_id IS '对外暴露的项目 UUID';
COMMENT ON COLUMN projects.user_id IS '所属用户 ID';
COMMENT ON COLUMN projects.name IS '项目名称';
COMMENT ON COLUMN projects.project_type IS '项目类型，如 question 或 note';
COMMENT ON COLUMN projects.summary IS '项目摘要';
COMMENT ON COLUMN projects.description IS '项目描述';
COMMENT ON COLUMN projects.color IS '前端展示颜色';
COMMENT ON COLUMN projects.icon IS '前端展示图标';
COMMENT ON COLUMN projects.is_default IS '是否为默认项目';
COMMENT ON COLUMN upload_batches.id IS '上传批次自增主键';
COMMENT ON COLUMN upload_batches.user_id IS '上传用户 ID';
COMMENT ON COLUMN upload_batches.project_id IS '所属项目 ID';
COMMENT ON COLUMN upload_batches.original_filename IS '原始文件名';
COMMENT ON COLUMN upload_batches.subject IS '科目';
COMMENT ON COLUMN upload_batches.file_path IS '上传文件存储路径';
COMMENT ON COLUMN upload_batches.upload_time IS '上传时间';

-- 题目与笔记字段注释
COMMENT ON COLUMN questions.id IS '题目自增主键';
COMMENT ON COLUMN questions.user_id IS '所属用户 ID';
COMMENT ON COLUMN questions.project_id IS '所属项目 ID';
COMMENT ON COLUMN questions.batch_id IS '来源上传批次 ID';
COMMENT ON COLUMN questions.content_hash IS '题目内容哈希，用于去重';
COMMENT ON COLUMN questions.question_type IS '题型';
COMMENT ON COLUMN questions.content_json IS '题干结构化 JSON';
COMMENT ON COLUMN questions.options_json IS '选项结构化 JSON';
COMMENT ON COLUMN questions.has_formula IS '是否包含公式';
COMMENT ON COLUMN questions.has_image IS '是否包含图片';
COMMENT ON COLUMN questions.image_refs_json IS '题目图片引用 JSON';
COMMENT ON COLUMN questions.needs_correction IS '是否需要人工校正';
COMMENT ON COLUMN questions.ocr_issues_json IS 'OCR 问题记录 JSON';
COMMENT ON COLUMN questions.user_answer IS '用户作答';
COMMENT ON COLUMN questions.answer IS '标准答案或解析答案';
COMMENT ON COLUMN questions.review_status IS '复习状态';
COMMENT ON COLUMN questions.review_due_at IS '下次应复习时间';
COMMENT ON COLUMN questions.review_last_at IS '上次复习时间';
COMMENT ON COLUMN questions.review_interval_days IS '当前复习间隔天数';
COMMENT ON COLUMN questions.review_count IS '复习次数';
COMMENT ON COLUMN questions.ease_factor IS '间隔复习难度系数';
COMMENT ON COLUMN notes.id IS '笔记自增主键';
COMMENT ON COLUMN notes.user_id IS '所属用户 ID';
COMMENT ON COLUMN notes.project_id IS '所属项目 ID';
COMMENT ON COLUMN notes.title IS '笔记标题';
COMMENT ON COLUMN notes.subject IS '科目';
COMMENT ON COLUMN notes.content_markdown IS '整理后的 Markdown 内容';
COMMENT ON COLUMN notes.source_images_json IS '来源图片路径列表 JSON';
COMMENT ON COLUMN notes.ocr_text IS 'OCR 原始文本';
COMMENT ON COLUMN notes.review_due_at IS '下次应复习时间';
COMMENT ON COLUMN notes.review_last_at IS '上次复习时间';
COMMENT ON COLUMN notes.review_interval_days IS '当前复习间隔天数';
COMMENT ON COLUMN notes.review_count IS '复习次数';
COMMENT ON COLUMN notes.ease_factor IS '间隔复习难度系数';

-- 标签、对话、设备和工作流字段注释
COMMENT ON COLUMN knowledge_tags.tag_name IS '知识点标签名称';
COMMENT ON COLUMN knowledge_tags.subject IS '所属科目';
COMMENT ON COLUMN question_tag_mapping.question_id IS '题目 ID';
COMMENT ON COLUMN question_tag_mapping.tag_id IS '知识点标签 ID';
COMMENT ON COLUMN note_tag_mapping.note_id IS '笔记 ID';
COMMENT ON COLUMN note_tag_mapping.tag_id IS '知识点标签 ID';
COMMENT ON COLUMN chat_sessions.public_id IS '对外暴露的会话 UUID';
COMMENT ON COLUMN chat_sessions.user_id IS '所属用户 ID';
COMMENT ON COLUMN chat_sessions.question_id IS '绑定题目 ID，可为空';
COMMENT ON COLUMN chat_sessions.title IS '会话标题';
COMMENT ON COLUMN chat_messages.session_id IS '所属会话 ID';
COMMENT ON COLUMN chat_messages.role IS '消息角色，如 user 或 assistant';
COMMENT ON COLUMN chat_messages.content IS '消息内容';
COMMENT ON COLUMN device_bindings.device_uuid IS '设备 UUID';
COMMENT ON COLUMN device_bindings.user_id IS '绑定用户 ID';
COMMENT ON COLUMN device_bindings.is_active IS '绑定是否有效';
COMMENT ON COLUMN device_captures.device_uuid IS '来源设备 UUID';
COMMENT ON COLUMN device_captures.user_id IS '所属用户 ID';
COMMENT ON COLUMN device_captures.file_key IS '文件业务键';
COMMENT ON COLUMN device_captures.original_filename IS '原始文件名';
COMMENT ON COLUMN device_captures.file_path IS '文件存储路径';
COMMENT ON COLUMN device_captures.content_type IS '文件 MIME 类型';
COMMENT ON COLUMN device_captures.file_size IS '文件大小，单位字节';
COMMENT ON COLUMN workflow_runs.public_id IS '对外暴露的运行 UUID';
COMMENT ON COLUMN workflow_runs.run_type IS '工作流类型';
COMMENT ON COLUMN workflow_runs.status IS '运行状态';
COMMENT ON COLUMN workflow_runs.result_dir IS '结果目录';
COMMENT ON COLUMN workflow_runs.error_message IS '错误信息';

-- 额度、模型选择、向量和复习字段注释
COMMENT ON COLUMN user_model_selections.user_id IS '所属用户 ID';
COMMENT ON COLUMN user_model_selections.category IS '模型类别';
COMMENT ON COLUMN user_model_selections.source IS '模型来源';
COMMENT ON COLUMN user_model_selections.provider_id IS '服务商配置 ID';
COMMENT ON COLUMN user_model_selections.model_name IS '模型名称';
COMMENT ON COLUMN user_model_selections.option_id IS '前端选项 ID';
COMMENT ON COLUMN quota_usage_events.user_id IS '所属用户 ID';
COMMENT ON COLUMN quota_usage_events.action_type IS '消耗动作类型';
COMMENT ON COLUMN quota_usage_events.amount IS '消耗额度数量';
COMMENT ON COLUMN quota_usage_events.summary IS '消耗摘要';
COMMENT ON COLUMN quota_usage_events.quota_date IS '额度日期，格式 YYYY-MM-DD';
COMMENT ON COLUMN question_embeddings.question_id IS '关联题目 ID';
COMMENT ON COLUMN question_embeddings.model_name IS '生成向量使用的模型';
COMMENT ON COLUMN question_embeddings.text_hash IS '向量来源文本哈希';
COMMENT ON COLUMN question_embeddings.vector_json IS '向量 JSON 数据';
COMMENT ON COLUMN review_events.user_id IS '复习用户 ID';
COMMENT ON COLUMN review_events.target_type IS '复习对象类型，如 question 或 note';
COMMENT ON COLUMN review_events.target_id IS '复习对象 ID';
COMMENT ON COLUMN review_events.rating IS '用户复习评价';
COMMENT ON COLUMN review_events.quality IS '复习质量评分';
COMMENT ON COLUMN review_events.interval_days IS '本次计算出的间隔天数';
COMMENT ON COLUMN review_events.ease_factor IS '本次计算后的难度系数';
COMMENT ON COLUMN review_events.reviewed_at IS '复习发生时间';
COMMENT ON COLUMN review_events.next_due_at IS '下次应复习时间';

COMMIT;
